use anyhow::{bail, Context, Result};
use colored::Colorize;
use pyllow_analyzer::analyze;
use pyllow_types::Issue;
use rustc_hash::FxHashMap;
use std::fs;
use std::path::{Path, PathBuf};

pub fn run(path: PathBuf, dry_run: bool, suppress: bool) -> Result<()> {
    let (config, root) = super::load_config(&path)?;
    let results = analyze(&config).context("analysis failed")?;

    if suppress {
        return write_suppress_entries(&results.issues, &root, dry_run);
    }

    let mut by_file: FxHashMap<PathBuf, Vec<(u32, String)>> = FxHashMap::default();
    for issue in &results.issues {
        if let Issue::UnusedImport {
            path, line, name, ..
        } = issue
        {
            by_file
                .entry(path.clone())
                .or_default()
                .push((*line, name.clone()));
        }
    }

    if by_file.is_empty() {
        println!("{} no unused imports to fix", "ok".green().bold());
        return Ok(());
    }

    let mut total_removed = 0usize;
    let mut total_skipped = 0usize;
    let mut files_changed = 0usize;
    let mut files_with_skips: Vec<(PathBuf, Vec<(u32, String)>)> = Vec::new();

    for (file_path, mut issues) in by_file {
        issues.sort_by(|a, b| b.0.cmp(&a.0));
        let raw = fs::read_to_string(&file_path)
            .with_context(|| format!("reading {}", file_path.display()))?;
        let mut lines: Vec<String> = raw.lines().map(String::from).collect();
        let trailing_newline = raw.ends_with('\n');

        let mut removed_in_file = 0usize;
        let mut skipped_in_file: Vec<(u32, String)> = Vec::new();

        for (line_no, name) in &issues {
            let idx = (*line_no as usize).saturating_sub(1);
            let Some(line) = lines.get(idx) else {
                skipped_in_file.push((*line_no, name.clone()));
                continue;
            };
            if can_safely_remove(line, name) {
                lines.remove(idx);
                removed_in_file += 1;
            } else {
                skipped_in_file.push((*line_no, name.clone()));
            }
        }

        if removed_in_file > 0 {
            total_removed += removed_in_file;
            files_changed += 1;
            if !dry_run {
                let mut out = lines.join("\n");
                if trailing_newline {
                    out.push('\n');
                }
                fs::write(&file_path, out)
                    .with_context(|| format!("writing {}", file_path.display()))?;
            }
            println!(
                "{} {} ({} removed)",
                if dry_run {
                    "would fix".yellow()
                } else {
                    "fixed".green()
                },
                file_path.display(),
                removed_in_file
            );
        }

        total_skipped += skipped_in_file.len();
        if !skipped_in_file.is_empty() {
            files_with_skips.push((file_path, skipped_in_file));
        }
    }

    println!();
    println!(
        "{} {} import{} {} across {} file{}",
        if dry_run {
            "would remove".yellow().bold()
        } else {
            "removed".green().bold()
        },
        total_removed,
        if total_removed == 1 { "" } else { "s" },
        if dry_run { "(dry run)" } else { "" }.dimmed(),
        files_changed,
        if files_changed == 1 { "" } else { "s" },
    );
    if total_skipped > 0 {
        println!(
            "{} {} import{} on multi-binding lines (manual edit required):",
            "skipped".dimmed(),
            total_skipped,
            if total_skipped == 1 { "" } else { "s" },
        );
        for (file, skips) in &files_with_skips {
            for (line, name) in skips {
                println!("  {}:{} {}", file.display(), line, name);
            }
        }
    }
    Ok(())
}

fn write_suppress_entries(issues: &[Issue], project_root: &Path, dry_run: bool) -> Result<()> {
    let mut entries: Vec<(String, &'static str, Option<u32>)> = Vec::new();
    for issue in issues {
        if matches!(issue, Issue::ParseError { .. }) {
            continue;
        }
        let abs = issue.path();
        if abs.as_os_str().is_empty() {
            continue;
        }
        let rel = abs.strip_prefix(project_root).unwrap_or(abs);
        let rel_str = rel.to_string_lossy().into_owned();
        if rel_str.is_empty() {
            continue;
        }
        entries.push((rel_str, issue.rule_key(), issue.line()));
    }

    if entries.is_empty() {
        println!("{} no suppressible issues found", "ok".green().bold());
        return Ok(());
    }

    let mut body = String::new();
    body.push_str("\n# Auto-generated by `pyllow fix --suppress`.\n");
    body.push_str("# Review each entry and add a `reason` so future maintainers know why.\n");
    for (path, rule, line) in &entries {
        body.push_str("\n[[suppress]]\n");
        body.push_str(&format!("path = {}\n", toml_string(path)));
        body.push_str(&format!("rules = [{}]\n", toml_string(rule)));
        if let Some(line) = line {
            body.push_str(&format!("line = {line}\n"));
        }
    }

    let config_path = project_root.join("pyllow.toml");
    let pyproject_path = project_root.join("pyproject.toml");
    // Config loading prefers pyllow.toml over pyproject.toml, so silently
    // creating a new pyllow.toml in a pyproject-configured project would
    // shadow every existing [tool.pyllow] setting. Refuse and tell the user
    // where to put the entries themselves.
    if !config_path.exists() && pyproject_has_tool_pyllow(&pyproject_path)? {
        bail!(
            "project is configured via [tool.pyllow] in pyproject.toml; \
             refusing to create pyllow.toml (it would shadow the existing config). \
             Re-run with --dry-run to preview the {n} entr{plural}, then paste them \
             under [tool.pyllow] in pyproject.toml as [[tool.pyllow.suppress]]",
            n = entries.len(),
            plural = if entries.len() == 1 { "y" } else { "ies" },
        );
    }
    if dry_run {
        println!(
            "{} would append {} entr{} to {}:",
            "dry-run".yellow().bold(),
            entries.len(),
            if entries.len() == 1 { "y" } else { "ies" },
            config_path.display()
        );
        print!("{body}");
        return Ok(());
    }

    let mut existing = fs::read_to_string(&config_path).unwrap_or_default();
    if !existing.is_empty() && !existing.ends_with('\n') {
        existing.push('\n');
    }
    existing.push_str(&body);
    fs::write(&config_path, existing)
        .with_context(|| format!("writing {}", config_path.display()))?;

    println!(
        "{} {} [[suppress]] entr{} to {}",
        "wrote".green().bold(),
        entries.len(),
        if entries.len() == 1 { "y" } else { "ies" },
        config_path.display()
    );
    Ok(())
}

/// TOML basic-string serialization for a path or rule key. Uses the `toml`
/// crate to handle escaping correctly (quotes, backslashes, non-ASCII).
fn toml_string(s: &str) -> String {
    toml::Value::String(s.to_string()).to_string()
}

/// True iff `pyproject.toml` exists and contains a `[tool.pyllow]` table.
/// Parses the file properly (vs substring matching) so a literal string
/// `"[tool.pyllow]"` somewhere in the file doesn't false-positive.
fn pyproject_has_tool_pyllow(path: &Path) -> Result<bool> {
    if !path.exists() {
        return Ok(false);
    }
    let text = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let parsed: toml::Value = match toml::from_str(&text) {
        Ok(v) => v,
        // Unparseable pyproject.toml isn't our concern here; assume not
        // configured rather than blocking the user on someone else's syntax.
        Err(_) => return Ok(false),
    };
    Ok(parsed.get("tool").and_then(|t| t.get("pyllow")).is_some())
}

fn can_safely_remove(line: &str, name: &str) -> bool {
    let trimmed = line.trim_start();
    let stripped = match trimmed.find('#') {
        Some(idx) => trimmed[..idx].trim_end(),
        None => trimmed.trim_end(),
    };
    if stripped.is_empty() {
        return false;
    }
    // `import <module>` — sole import; bound name is name
    if let Some(rest) = stripped.strip_prefix("import ") {
        if rest.contains(',') || rest.contains('(') {
            return false;
        }
        if let Some((module, alias)) = rest.split_once(" as ") {
            return alias.trim() == name && !module.contains(',');
        }
        let first_segment = rest.split('.').next().unwrap_or("").trim();
        return first_segment == name;
    }
    // `from <module> import <name>` or `from <module> import <name> as <alias>`
    if let Some(rest) = stripped.strip_prefix("from ") {
        let Some(import_idx) = rest.find(" import ") else {
            return false;
        };
        let import_part = rest[import_idx + " import ".len()..].trim();
        if import_part.contains(',') || import_part.starts_with('(') {
            return false;
        }
        if let Some((bound_name, alias)) = import_part.split_once(" as ") {
            return alias.trim() == name && !bound_name.contains(',');
        }
        return import_part == name;
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn safely_removes_simple_import() {
        assert!(can_safely_remove("import os", "os"));
        assert!(can_safely_remove("import os  ", "os"));
        assert!(can_safely_remove("    import os", "os"));
        assert!(can_safely_remove("import os  # noqa: ignored", "os"));
    }

    #[test]
    fn safely_removes_aliased_import() {
        assert!(can_safely_remove("import numpy as np", "np"));
    }

    #[test]
    fn safely_removes_dotted_import() {
        assert!(can_safely_remove("import os.path", "os"));
    }

    #[test]
    fn safely_removes_from_import() {
        assert!(can_safely_remove("from typing import List", "List"));
        assert!(can_safely_remove("from typing import List as L", "L"));
    }

    #[test]
    fn refuses_multi_binding_lines() {
        assert!(!can_safely_remove("import os, sys", "os"));
        assert!(!can_safely_remove("from typing import List, Dict", "List"));
    }

    #[test]
    fn refuses_paren_grouped_imports() {
        assert!(!can_safely_remove("from typing import (List)", "List"));
        assert!(!can_safely_remove("from typing import (", "List"));
    }

    #[test]
    fn refuses_unrelated_lines() {
        assert!(!can_safely_remove("x = 1", "x"));
        assert!(!can_safely_remove("def import_data():", "data"));
    }

    #[test]
    fn toml_string_escapes_special_chars() {
        // Path strings should round-trip through a TOML parser.
        let original = r#"path with "quote" and \backslash"#;
        let serialized = toml_string(original);
        let toml_doc = format!("v = {serialized}");
        let parsed: toml::Value = toml::from_str(&toml_doc).unwrap();
        assert_eq!(parsed["v"].as_str().unwrap(), original);
    }

    #[test]
    fn write_suppress_creates_pyllow_toml_with_entries() {
        let dir = tempfile::tempdir().unwrap();
        let project = dir.path();
        let foo = project.join("src").join("foo.py");
        fs::create_dir_all(foo.parent().unwrap()).unwrap();
        fs::write(&foo, "import os\n").unwrap();

        let issues = vec![Issue::UnusedImport {
            path: foo,
            line: 1,
            name: "os".into(),
            module: "os".into(),
        }];

        write_suppress_entries(&issues, project, false).unwrap();

        let written = fs::read_to_string(project.join("pyllow.toml")).unwrap();
        assert!(written.contains("[[suppress]]"));
        assert!(written.contains(r#"path = "src/foo.py""#));
        assert!(written.contains(r#"rules = ["unused-import"]"#));
        assert!(written.contains("line = 1"));
    }

    #[test]
    fn write_suppress_appends_to_existing_pyllow_toml() {
        let dir = tempfile::tempdir().unwrap();
        let project = dir.path();
        // Existing config with a comment that must survive.
        fs::write(
            project.join("pyllow.toml"),
            "# Important comment that must stay\npackageRoots = [\"src\"]\n",
        )
        .unwrap();

        let foo = project.join("src").join("foo.py");
        fs::create_dir_all(foo.parent().unwrap()).unwrap();
        fs::write(&foo, "").unwrap();

        let issues = vec![Issue::UnusedFile { path: foo }];
        write_suppress_entries(&issues, project, false).unwrap();

        let written = fs::read_to_string(project.join("pyllow.toml")).unwrap();
        assert!(
            written.contains("# Important comment that must stay"),
            "appending must preserve existing comments"
        );
        assert!(written.contains("packageRoots = [\"src\"]"));
        assert!(written.contains("[[suppress]]"));
        assert!(written.contains(r#"rules = ["unused-file"]"#));
        // UnusedFile has no line — entry should omit the line key.
        let suppress_block = written.split("[[suppress]]").nth(1).unwrap();
        assert!(!suppress_block.contains("line ="));
    }

    #[test]
    fn write_suppress_refuses_when_pyproject_has_tool_pyllow() {
        // Project uses pyproject.toml for config. Creating pyllow.toml here
        // would silently shadow [tool.pyllow] on subsequent runs because
        // config loading prefers pyllow.toml — Pi P1 regression.
        let dir = tempfile::tempdir().unwrap();
        let project = dir.path();
        fs::write(
            project.join("pyproject.toml"),
            "[tool.pyllow]\npackageRoots = [\"src\"]\n",
        )
        .unwrap();
        let foo = project.join("src").join("foo.py");
        fs::create_dir_all(foo.parent().unwrap()).unwrap();
        fs::write(&foo, "").unwrap();
        let issues = vec![Issue::UnusedFile { path: foo }];

        let err = write_suppress_entries(&issues, project, false).unwrap_err();
        assert!(
            err.to_string().contains("pyproject.toml"),
            "expected guidance about pyproject.toml; got: {err}"
        );
        // And the file MUST NOT be created — that's the whole point.
        assert!(
            !project.join("pyllow.toml").exists(),
            "pyllow.toml should not have been created"
        );
    }

    #[test]
    fn write_suppress_dry_run_does_not_write_file() {
        let dir = tempfile::tempdir().unwrap();
        let project = dir.path();
        let foo = project.join("src").join("foo.py");
        fs::create_dir_all(foo.parent().unwrap()).unwrap();
        fs::write(&foo, "").unwrap();

        let issues = vec![Issue::UnusedFile { path: foo }];
        write_suppress_entries(&issues, project, true).unwrap();

        assert!(!project.join("pyllow.toml").exists());
    }
}
